const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Behaviors.solid,
		C3.Behaviors.Anchor,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Universo: 0},
	{"8Direções": 0},
	{CentrarEm: 0},
	{"8Direções2": 0},
	{RestritoAoLayout: 0},
	{SuperTuba: 0},
	{Start: 0},
	{SuperTubaUniverso: 0},
	{parabensPerder: 0},
	{reiniciar: 0},
	{youWin: 0},
	{Girar: 0},
	{estrela: 0},
	{MoverPara: 0},
	{panthom: 0},
	{Sólido: 0},
	{satelite: 0},
	{Âncora: 0},
	{estrelaTexto: 0},
	{estrelaValor: 0},
	{phantonwin: 0},
	{Mouse: 0},
	{TubaWin: 0},
	{TubaInicio: 0},
	{Áudio: 0}
];

self.InstanceType = {
	Universo: class extends self.ISpriteInstance {},
	SuperTuba: class extends self.ISpriteInstance {},
	Start: class extends self.ISpriteInstance {},
	SuperTubaUniverso: class extends self.ITextInstance {},
	parabensPerder: class extends self.ITextInstance {},
	reiniciar: class extends self.ISpriteInstance {},
	youWin: class extends self.ITextInstance {},
	estrela: class extends self.ISpriteInstance {},
	panthom: class extends self.ISpriteInstance {},
	satelite: class extends self.ISpriteInstance {},
	estrelaTexto: class extends self.ITextInstance {},
	estrelaValor: class extends self.ITextInstance {},
	phantonwin: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	TubaWin: class extends self.ISpriteInstance {},
	TubaInicio: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {}
}